version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
